output.path: &output-path "target/moe-moe-secretary.jar"
output.name: &output-name "moe-moe-secretary.jar"
target.users: &target-users "[487353090]"

name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -q -ntp -B package

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: *output-name # Artifact name
        path: *output-path # Directory containing files to upload

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install requirements
      run: python3 -m pip -q install -r .github/workflows/requirements.txt

    - name: Deploy to Telegram
      env: # Or as an environment variable
        BOT_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
        TARGET_CHAT_IDS: *target-users
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        ARTIFACT: *output-path
        SHA7: ${GITHUB_SHA:7}
      run: python3 .github/workflows/deployer.py
